server:
  port: 8504
spring:
  cloud:
    function:
      definition: transform;upper;ending;process;dlq
    stream:
      bindings:
        numberProducer-out-0:
          destination: input-topic
        upper-in-0:
          destination: input-topic
        upper-out-0:
          destination: output-topic
        transform-in-0:
          destination: input-topic
          group: wordGroup
          consumer:
            auto-bind-dlq: true
        transform-out-0:
          destination: output-topic
        ending-in-0:
          destination: input-topic
        ending-out-0:
          destination: output-topic
        process-in-0:
          destination: input-topic
        process-out-0:
          destination: output-topic
        dlq-out-0:
          destination: error-input-topic
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            commit.interval.ms: 100
            schema.registry.url: http://localhost:8081
            default:
              key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde